project:
  type: website
  resources: 
    - img/wurom_ase_wurom.jpeg
    - 404.html

website:
  title: "Berom Language and Translation Board"

  favicon: /img/favicon.ico
  navbar:
    pinned: true
    logo: /img/BLTB_Logo_pure.jpg
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog/index.qmd
        text: Blog
      - href: News/index.qmd
        text: News

format:
  html:
    theme: cosmo
    include-after-body: chatbot.html
    css: styles.css
    toc: true



